dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
install:
  - ./mvnw package
deploy:
  provider: releases
  api_key:
    secure: uP3+B3uW0GAbEbPRfBjCY8RsR9YOnw7jzfFL8x8oyCczzLz+bAhs3fmZF7cZvUZL/Nw1BSCrIDK0IfrHw3qGFhGzP+W4mgg6jrhYbC6M2sHCMaqWJmBgun2F8K9vKxrlel5siJgyyNl92p1YIZnYzN0zOOzZFBcsNF6iYoDrs2rGjwxxCQEECgxY5rt2F00Lw7JNHhyR1tbnScTSvH54Mbq9IWoqYHWBiKqdDufvMOfQi3nHWUuDcOm55I1L2sumQLMpu2Di7bELBAh8TOAR2W7aHGyPnQdrYyFsueTCpQWNRxFr0zOl3vvAkNWZJdMuMW8RAAKPPdOmY8UfLZGP7Piavq8zo9363eadxI19Zja/5QdK6NWHOeSr/SYS4ihCHPHl2LqBDYaWgAAEZzUt4KaCgTMlq+V4d1InwYxA0mpcN7I267QOnusjtMNCwRwx4YU2I9EuE/dAWvopPJiy8J6py5jlkrYHggeypQKsK+Q+wi4YKh5pKcxL1X4v0gJiUH0AlftZO9YFF6+RGgxnXM965hk+sZFfnFb25FatRhNRZGrhijwIitdL9rgvAayPmYjzMIz5j727IePYBYYU5xCVoJl/zYr0RkLj8I6N5sA5wtAtoi3xOF0/v8Zb3HeIITNnk2sgNzQ2Y84aGXWc9rfI9jOTd+bDlT/fl6uwRLY=
  file: target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
  skip_cleanup: true
  # Modify this to build on every commit
  on:
    branch: master
