dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
- "./mvnw package"
deploy:
  provider: releases
  api_key:
    secure: "bjNNzwZ79DMvyTgj9XGhunul0WBMBt6tnH8thw3hC23AxL/FUtRbkWiMXJcJTl80QoMV+AyD91qT34sj+Voxwkh6tVupE9oOywlmmPUodDWzT9wOhRBh4K76rfqQZ+u+eXbzPqk4BfufYR36EOXYfrtSHcgVCQ4u0eJJLuJxnumTCaiHKU0dQ6TQ93s40ZC6ZjccQ86o/prCYzHALpVNfHNiD2h//jZFHCCOGyJOoTELV/O64uDnqfsN58Etjmdonh/mITnD8xCCCJjoWuVa74AIsveWyPXrCUgX9OvjkPFFD7qxwcxH4sqCiOnqTkEE9XR00XR0Ke2DmnOXxFoMUN3rf1+4vWUg0hRLL5zSA6q/fJvwhzxVDflO/w+yslnx3V2SRijGfq+M9lSPkAQBKoeXG1ZT4yGiRZIGdolcNEvTepHvs1Ena3SKhn48TVF5+HVW0R53Khs2n0SReCsO8tBwsLnlgzfJw15rUq+FPkN2w8n+xMbe/6+z4Nd4k9gqq1naP7i+iol+HusTiqttSm+QZbEBiyWXPXUXpf87thFCtaWD+K6OW246yZNNojTN0544KHQ14mh6BOKQ6qotmE9JPK8pBa2kj0+OU/F6ho5i7JI37FgTZz9+4/v/wpq2XxyitoQERrI3plrV81vzMOShjdO2PHcFggWsWPAmGNw="
  file: target/*.jar
  skip_cleanup: true
  on:
    branch: main
